const customers = [
    
        {
          "id": "C001",
          "grossIncome": 4585,
          "employmentStatus": "Unemployed",
          "creditScore": 639,
          "totalMonthlyDebtPayments": 1153,
          "totalMonthlyIncome": 3695,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": 0.24
        },
        {
          "id": "C002",
          "grossIncome": 5937,
          "employmentStatus": "Employed",
          "creditScore": 765,
          "totalMonthlyDebtPayments": 1346,
          "totalMonthlyIncome": 3597,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": 0.12
        },
        {
          "id": "C003",
          "grossIncome": 5637,
          "employmentStatus": "Employed",
          "creditScore": 620,
          "totalMonthlyDebtPayments": 1635,
          "totalMonthlyIncome": 3116,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": 0.16
        },
        {
          "id": "C004",
          "grossIncome": 7238,
          "employmentStatus": "Self-Employed",
          "creditScore": 832,
          "totalMonthlyDebtPayments": 936,
          "totalMonthlyIncome": 5906,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "46%"
        },
        {
          "id": "C005",
          "grossIncome": 6214,
          "employmentStatus": "Unemployed",
          "creditScore": 692,
          "totalMonthlyDebtPayments": 978,
          "totalMonthlyIncome": 6845,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "27%"
        },
        {
          "id": "C006",
          "grossIncome": 5764,
          "employmentStatus": "Self-Employed",
          "creditScore": 735,
          "totalMonthlyDebtPayments": 936,
          "totalMonthlyIncome": 5637,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "15%"
        },
        {
          "id": "C007",
          "grossIncome": 5475,
          "employmentStatus": "Self-Employed",
          "creditScore": 785,
          "totalMonthlyDebtPayments": 1255,
          "totalMonthlyIncome": 6340,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "32%"
        },
        {
          "id": "C008",
          "grossIncome": 7907,
          "employmentStatus": "Unemployed",
          "creditScore": 712,
          "totalMonthlyDebtPayments": 1757,
          "totalMonthlyIncome": 4065,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "45%"
        },
        {
          "id": "C009",
          "grossIncome": 4547,
          "employmentStatus": "Unemployed",
          "creditScore": 619,
          "totalMonthlyDebtPayments": 1688,
          "totalMonthlyIncome": 5457,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "19%"
        },
        {
          "id": "C010",
          "grossIncome": 7826,
          "employmentStatus": "Self-Employed",
          "creditScore": 626,
          "totalMonthlyDebtPayments": 1985,
          "totalMonthlyIncome": 3504,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "9%"
        },
        {
          "id": "C011",
          "grossIncome": 4582,
          "employmentStatus": "Unemployed",
          "creditScore": 754,
          "totalMonthlyDebtPayments": 800,
          "totalMonthlyIncome": 3607,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "5%"
        },
        {
          "id": "C012",
          "grossIncome": 4153,
          "employmentStatus": "Employed",
          "creditScore": 736,
          "totalMonthlyDebtPayments": 1499,
          "totalMonthlyIncome": 4921,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "13%"
        },
        {
          "id": "C013",
          "grossIncome": 4184,
          "employmentStatus": "Employed",
          "creditScore": 660,
          "totalMonthlyDebtPayments": 1908,
          "totalMonthlyIncome": 5406,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "30%"
        },
        {
          "id": "C014",
          "grossIncome": 5091,
          "employmentStatus": "Unemployed",
          "creditScore": 606,
          "totalMonthlyDebtPayments": 1266,
          "totalMonthlyIncome": 5192,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "27%"
        },
        {
          "id": "C015",
          "grossIncome": 5892,
          "employmentStatus": "Employed",
          "creditScore": 748,
          "totalMonthlyDebtPayments": 1116,
          "totalMonthlyIncome": 3266,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "28%"
        },
        {
          "id": "C016",
          "grossIncome": 7169,
          "employmentStatus": "Unemployed",
          "creditScore": 811,
          "totalMonthlyDebtPayments": 880,
          "totalMonthlyIncome": 7478,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "14%"
        },
        {
          "id": "C017",
          "grossIncome": 7184,
          "employmentStatus": "Employed",
          "creditScore": 727,
          "totalMonthlyDebtPayments": 1974,
          "totalMonthlyIncome": 6115,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "10%"
        },
        {
          "id": "C018",
          "grossIncome": 4602,
          "employmentStatus": "Unemployed",
          "creditScore": 819,
          "totalMonthlyDebtPayments": 1045,
          "totalMonthlyIncome": 6958,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "23%"
        },
        {
          "id": "C019",
          "grossIncome": 5280,
          "employmentStatus": "Unemployed",
          "creditScore": 737,
          "totalMonthlyDebtPayments": 1319,
          "totalMonthlyIncome": 6561,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "34%"
        },
        {
          "id": "C020",
          "grossIncome": 5971,
          "employmentStatus": "Self-Employed",
          "creditScore": 650,
          "totalMonthlyDebtPayments": 875,
          "totalMonthlyIncome": 3695,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "26%"
        },
        {
          "id": "C021",
          "grossIncome": 7241,
          "employmentStatus": "Self-Employed",
          "creditScore": 723,
          "totalMonthlyDebtPayments": 1140,
          "totalMonthlyIncome": 5846,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "12%"
        },
        {
          "id": "C022",
          "grossIncome": 6957,
          "employmentStatus": "Self-Employed",
          "creditScore": 728,
          "totalMonthlyDebtPayments": 1686,
          "totalMonthlyIncome": 7800,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "31%"
        },
        {
          "id": "C023",
          "grossIncome": 5152,
          "employmentStatus": "Unemployed",
          "creditScore": 666,
          "totalMonthlyDebtPayments": 922,
          "totalMonthlyIncome": 7458,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "8%"
        },
        {
          "id": "C024",
          "grossIncome": 4471,
          "employmentStatus": "Unemployed",
          "creditScore": 600,
          "totalMonthlyDebtPayments": 913,
          "totalMonthlyIncome": 5238,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "12%"
        },
        {
          "id": "C025",
          "grossIncome": 5055,
          "employmentStatus": "Unemployed",
          "creditScore": 688,
          "totalMonthlyDebtPayments": 1200,
          "totalMonthlyIncome": 6819,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "37%"
        },
        {
          "id": "C026",
          "grossIncome": 4662,
          "employmentStatus": "Unemployed",
          "creditScore": 761,
          "totalMonthlyDebtPayments": 1097,
          "totalMonthlyIncome": 7059,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "No",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "33%"
        },
        {
          "id": "C027",
          "grossIncome": 5026,
          "employmentStatus": "Employed",
          "creditScore": 799,
          "totalMonthlyDebtPayments": 996,
          "totalMonthlyIncome": 4711,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "43%"
        },
        {
          "id": "C028",
          "grossIncome": 5289,
          "employmentStatus": "Employed",
          "creditScore": 745,
          "totalMonthlyDebtPayments": 804,
          "totalMonthlyIncome": 7194,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "14%"
        },
        {
          "id": "C029",
          "grossIncome": 6803,
          "employmentStatus": "Employed",
          "creditScore": 805,
          "totalMonthlyDebtPayments": 841,
          "totalMonthlyIncome": 4440,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "42%"
        },
        {
          "id": "C030",
          "grossIncome": 4443,
          "employmentStatus": "Unemployed",
          "creditScore": 746,
          "totalMonthlyDebtPayments": 1510,
          "totalMonthlyIncome": 3927,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "37%"
        },
        {
          "id": "C031",
          "grossIncome": 4958,
          "employmentStatus": "Self-Employed",
          "creditScore": 781,
          "totalMonthlyDebtPayments": 1446,
          "totalMonthlyIncome": 7837,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "No",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "15%"
        },
        {
          "id": "C032",
          "grossIncome": 7369,
          "employmentStatus": "Unemployed",
          "creditScore": 788,
          "totalMonthlyDebtPayments": 1424,
          "totalMonthlyIncome": 4952,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "17%"
        },
        {
          "id": "C033",
          "grossIncome": 7344,
          "employmentStatus": "Unemployed",
          "creditScore": 748,
          "totalMonthlyDebtPayments": 1417,
          "totalMonthlyIncome": 7301,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "31%"
        },
        {
          "id": "C034",
          "grossIncome": 7888,
          "employmentStatus": "Employed",
          "creditScore": 632,
          "totalMonthlyDebtPayments": 1484,
          "totalMonthlyIncome": 4484,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "36%"
        },
        {
          "id": "C035",
          "grossIncome": 5644,
          "employmentStatus": "Self-Employed",
          "creditScore": 619,
          "totalMonthlyDebtPayments": 1171,
          "totalMonthlyIncome": 4212,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "46%"
        },
        {
          "id": "C036",
          "grossIncome": 4516,
          "employmentStatus": "Self-Employed",
          "creditScore": 639,
          "totalMonthlyDebtPayments": 1316,
          "totalMonthlyIncome": 4962,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "10%"
        },
        {
          "id": "C037",
          "grossIncome": 7419,
          "employmentStatus": "Unemployed",
          "creditScore": 651,
          "totalMonthlyDebtPayments": 1127,
          "totalMonthlyIncome": 5007,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "31%"
        },
        {
          "id": "C038",
          "grossIncome": 7611,
          "employmentStatus": "Employed",
          "creditScore": 758,
          "totalMonthlyDebtPayments": 1323,
          "totalMonthlyIncome": 3832,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "31%"
        },
        {
          "id": "C039",
          "grossIncome": 4186,
          "employmentStatus": "Employed",
          "creditScore": 621,
          "totalMonthlyDebtPayments": 879,
          "totalMonthlyIncome": 5354,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "32%"
        },
        {
          "id": "C040",
          "grossIncome": 4702,
          "employmentStatus": "Employed",
          "creditScore": 789,
          "totalMonthlyDebtPayments": 1487,
          "totalMonthlyIncome": 6216,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "26%"
        },
        {
          "id": "C041",
          "grossIncome": 7086,
          "employmentStatus": "Unemployed",
          "creditScore": 693,
          "totalMonthlyDebtPayments": 1539,
          "totalMonthlyIncome": 7534,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "49%"
        },
        {
          "id": "C042",
          "grossIncome": 4746,
          "employmentStatus": "Employed",
          "creditScore": 601,
          "totalMonthlyDebtPayments": 1972,
          "totalMonthlyIncome": 6855,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "20%"
        },
        {
          "id": "C043",
          "grossIncome": 4209,
          "employmentStatus": "Unemployed",
          "creditScore": 836,
          "totalMonthlyDebtPayments": 1610,
          "totalMonthlyIncome": 7252,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "20%"
        },
        {
          "id": "C044",
          "grossIncome": 4762,
          "employmentStatus": "Self-Employed",
          "creditScore": 734,
          "totalMonthlyDebtPayments": 907,
          "totalMonthlyIncome": 5972,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "38%"
        },
        {
          "id": "C045",
          "grossIncome": 4155,
          "employmentStatus": "Unemployed",
          "creditScore": 755,
          "totalMonthlyDebtPayments": 1969,
          "totalMonthlyIncome": 7158,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "48%"
        },
        {
          "id": "C046",
          "grossIncome": 4928,
          "employmentStatus": "Unemployed",
          "creditScore": 816,
          "totalMonthlyDebtPayments": 1933,
          "totalMonthlyIncome": 5627,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "33%"
        },
        {
          "id": "C047",
          "grossIncome": 5057,
          "employmentStatus": "Employed",
          "creditScore": 733,
          "totalMonthlyDebtPayments": 1890,
          "totalMonthlyIncome": 3534,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "28%"
        },
        {
          "id": "C048",
          "grossIncome": 4969,
          "employmentStatus": "Employed",
          "creditScore": 682,
          "totalMonthlyDebtPayments": 1223,
          "totalMonthlyIncome": 4076,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "No",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "42%"
        },
        {
          "id": "C049",
          "grossIncome": 5866,
          "employmentStatus": "Employed",
          "creditScore": 626,
          "totalMonthlyDebtPayments": 1604,
          "totalMonthlyIncome": 3870,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "No",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "36%"
        },
        {
          "id": "C050",
          "grossIncome": 7410,
          "employmentStatus": "Employed",
          "creditScore": 756,
          "totalMonthlyDebtPayments": 1233,
          "totalMonthlyIncome": 6666,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "43%"
        },
        {
          "id": "C051",
          "grossIncome": 8000,
          "employmentStatus": "Employed",
          "creditScore": 756,
          "totalMonthlyDebtPayments": 1233,
          "totalMonthlyIncome": 6666,
          "historyOfDefaultingLoans": "No",
          "criminalActivity": "No",
          "suspiciousBehavior": "No",
          "unverifiedEmployment": "No",
          "isDefaulter": "No",
          "frequentAddressChanges": "No",
          "involvedInMoneyLaundering": "No",
          "usingMultipleAlliances": "No",
          "debtToIncomeRatio": "43%"
        },
        {
          "id": "C052",
          "grossIncome": 8000,
          "employmentStatus": "Employed",
          "creditScore": 756,
          "totalMonthlyDebtPayments": 1233,
          "totalMonthlyIncome": 6666,
          "historyOfDefaultingLoans": "Yes",
          "criminalActivity": "Yes",
          "suspiciousBehavior": "Yes",
          "unverifiedEmployment": "Yes",
          "isDefaulter": "Yes",
          "frequentAddressChanges": "Yes",
          "involvedInMoneyLaundering": "Yes",
          "usingMultipleAlliances": "Yes",
          "debtToIncomeRatio": "43%"
        }
      
          
      
];
